package com.warungerik.devidchanger.ui.theme

import com.warungerik.devidchanger.model.AppLanguage

class AppStrings(val language: AppLanguage) {

    val appName = "DEVID CHANGER"
    val subtitle = "Mobile Legends Device ID Changer Tool"
    
    val tabHome = if (language == AppLanguage.INDONESIAN) "Home" else "Home"
    val tabInfo = if (language == AppLanguage.INDONESIAN) "Info" else "Info"
    val tabSettings = if (language == AppLanguage.INDONESIAN) "Pengaturan" else "Settings"

    val rootStatusTitle = if (language == AppLanguage.INDONESIAN) "STATUS AKSES ROOT" else "ROOT ACCESS STATUS"

    val rootTypeLabel = if (language == AppLanguage.INDONESIAN) "Tipe Root" else "Root Type"
    val selinuxLabel = "SELinux Status"
    val rootVerified = if (language == AppLanguage.INDONESIAN) "Terverifikasi" else "Verified"
    val rootNotDetected = if (language == AppLanguage.INDONESIAN) "Tidak Terdeteksi" else "Not Detected"

    val versionSelectorTitle = if (language == AppLanguage.INDONESIAN) "PILIH VERSI MLBB" else "SELECT MLBB VERSION"

    val appInfoTitle = if (language == AppLanguage.INDONESIAN) "INFORMASI APLIKASI" else "APPLICATION INFORMATION"
    val labelAppName = if (language == AppLanguage.INDONESIAN) "Nama Aplikasi" else "Application Name"
    val labelPackageName = "Package Name"
    val labelVersion = if (language == AppLanguage.INDONESIAN) "Versi Aplikasi" else "App Version"
    val labelDeveloper = "Developer"
    val labelCopyright = "Copyright"
    val btnContactDev = if (language == AppLanguage.INDONESIAN) "HUBUNGI DEVELOPER" else "CONTACT DEVELOPER"

    val currentJsonIdTitle = "CURRENT JSONDEVICEID"
    val fileNotFound = if (language == AppLanguage.INDONESIAN) "File tidak ditemukan (Game belum terinstal/dibuka)" else "File not found (Game not installed/opened)"
    val notFound = if (language == AppLanguage.INDONESIAN) "Tidak ditemukan" else "Not found"
    
    val btnCopy = if (language == AppLanguage.INDONESIAN) "Salin" else "Copy"
    val btnPaste = if (language == AppLanguage.INDONESIAN) "Tempel" else "Paste"
    val btnRandomGuest = if (language == AppLanguage.INDONESIAN) "Acak Guest" else "Random Guest"
    
    val newJsonIdTitle = if (language == AppLanguage.INDONESIAN) "JSONDEVICEID BARU" else "NEW JSONDEVICEID"
    val placeholderNewJsonId = if (language == AppLanguage.INDONESIAN) "Klik 'Acak Guest' atau 'Tempel' ID di sini..." else "Click 'Random Guest' or 'Paste' ID here..."

    fun idLength(len: Int) = if (language == AppLanguage.INDONESIAN) "Panjang ID: $len karakter" else "ID Length: $len characters"
    val usaCharOk = "USA 84 Char OK"
    val usaCharNeed = if (language == AppLanguage.INDONESIAN) "USA butuh 84 Char" else "USA needs 84 Char"

    val btnExecute = if (language == AppLanguage.INDONESIAN) "JALANKAN INJEKSI DEVID" else "EXECUTE DEVID INJECTION"
    val processing = if (language == AppLanguage.INDONESIAN) "MEMPROSES INJEKSI..." else "PROCESSING INJECTION..."

    val logTitle = if (language == AppLanguage.INDONESIAN) "TERMINAL LOG OPERASI" else "OPERATION TERMINAL LOG"
    val clearLogs = if (language == AppLanguage.INDONESIAN) "Bersihkan Log" else "Clear Logs"
    val emptyLogs = if (language == AppLanguage.INDONESIAN) "Belum ada log operasi..." else "No operation logs yet..."

    val welcomeTitle = if (language == AppLanguage.INDONESIAN) "SELAMAT DATANG!" else "WELCOME!"
    val welcomeSubtitle = "DEVID CHANGER"
    val welcomeDev = "Developer: @WARUNG_ERIK"
    val feature1Title = if (language == AppLanguage.INDONESIAN) "Support Semua Versi MLBB" else "Supports All MLBB Versions"
    val feature1Desc = "Global, India, USA, VN, HWAG, LITE"
    val feature2Title = if (language == AppLanguage.INDONESIAN) "Support Semua Tipe Root" else "Supports All Root Types"
    val feature2Desc = "Magisk, KernelSU, APatch, SuperSU"
    val feature3Title = if (language == AppLanguage.INDONESIAN) "Acak Guest (Random ID)" else "Random Guest (Random ID)"
    val feature3Desc = if (language == AppLanguage.INDONESIAN) "Generate ID Guest baru otomatis" else "Generate new Guest ID automatically"
    val feature4Title = if (language == AppLanguage.INDONESIAN) "Backup Otomatis" else "Automatic Backup"
    val feature4Desc = if (language == AppLanguage.INDONESIAN) "Disimpan di /storage/emulated/0/Tyasimut" else "Saved in /storage/emulated/0/Tyasimut"
    val btnContinue = if (language == AppLanguage.INDONESIAN) "LANJUTKAN" else "CONTINUE"

    val themeSettingsTitle = if (language == AppLanguage.INDONESIAN) "PENGATURAN TEMA" else "THEME SETTINGS"
    val darkModeLabel = if (language == AppLanguage.INDONESIAN) "Mode Gelap (Dark Mode)" else "Dark Mode"
    val darkModeActive = if (language == AppLanguage.INDONESIAN) "Aktif (Tampilan Gelap)" else "Enabled (Dark Theme)"
    val darkModeInactive = if (language == AppLanguage.INDONESIAN) "Nonaktif (Tampilan Terang)" else "Disabled (Light Theme)"
    val optionDark = if (language == AppLanguage.INDONESIAN) "Mode Gelap (Dark)" else "Dark Theme"
    val optionLight = if (language == AppLanguage.INDONESIAN) "Mode Terang (Light)" else "Light Theme"
    val langSettingsTitle = if (language == AppLanguage.INDONESIAN) "PENGATURAN BAHASA" else "LANGUAGE SETTINGS"
    val selectLangSub = if (language == AppLanguage.INDONESIAN) "Pilih bahasa tampilan aplikasi:" else "Select application display language:"
    
    val toastCopySuccess = if (language == AppLanguage.INDONESIAN) "ID berhasil disalin!" else "ID copied successfully!"
    val toastPasteSuccess = if (language == AppLanguage.INDONESIAN) "ID berhasil ditempel dari clipboard!" else "ID pasted from clipboard!"
    val toastPasteEmpty = if (language == AppLanguage.INDONESIAN) "Clipboard kosong!" else "Clipboard is empty!"
    val toastRandomSuccess = if (language == AppLanguage.INDONESIAN) "ID Guest Baru (Random) berhasil dibuat!" else "New Random Guest ID created!"

    val processingTitle = if (language == AppLanguage.INDONESIAN) "MEMPROSES INJEKSI DEVID" else "PROCESSING DEVID INJECTION"
    val processingSub = if (language == AppLanguage.INDONESIAN) "Mohon tunggu, jangan tutup aplikasi..." else "Please wait, do not close the app..."
    val stepStoppingGame = if (language == AppLanguage.INDONESIAN) "Menghentikan proses game..." else "Stopping game process..."
    val stepCreatingBackup = if (language == AppLanguage.INDONESIAN) "Membuat backup konfigurasi..." else "Backing up configuration..."
    val stepInjectingId = if (language == AppLanguage.INDONESIAN) "Menginjeksikan Device ID baru..." else "Injecting new Device ID..."
    val stepFixingPermissions = if (language == AppLanguage.INDONESIAN) "Memperbaiki perizinan file..." else "Fixing file permissions..."
    val stepFinishing = if (language == AppLanguage.INDONESIAN) "Finalisasi..." else "Finishing up..."

    fun logRootVerified(type: String, version: String) = if (language == AppLanguage.INDONESIAN) "Akses Root terverifikasi ($type $version)" else "Root access verified ($type $version)"
    val logRootNotFound = if (language == AppLanguage.INDONESIAN) "Error: Akses Root tidak ditemukan!" else "Error: Root access not found!"
    val logRootRequired = if (language == AppLanguage.INDONESIAN) "Gagal: Akses Root diperlukan!" else "Failed: Root access required!"
    val logInputEmpty = if (language == AppLanguage.INDONESIAN) "Error: Input JsonDeviceID tidak boleh kosong!" else "Error: JsonDeviceID input cannot be empty!"
    fun logRandomGuestCreated(id: String) = if (language == AppLanguage.INDONESIAN) "ID Guest Baru (Random) dibuat: $id" else "New Random Guest ID created: $id"
    fun logFolderNotFound(version: String, pkg: String) = if (language == AppLanguage.INDONESIAN) "Folder data $version ($pkg) tidak ditemukan." else "Data folder for $version ($pkg) not found."
    fun logStartInjection(version: String) = if (language == AppLanguage.INDONESIAN) "Memulai proses injeksi DevID untuk $version" else "Starting DevID injection process for $version"
    fun logStoppingGame(version: String, pkg: String) = if (language == AppLanguage.INDONESIAN) "Menghentikan $version ($pkg)..." else "Stopping $version ($pkg)..."
    val logCreatingBackup = if (language == AppLanguage.INDONESIAN) "Membuat backup file sebelum diubah..." else "Creating file backup before modification..."
    fun logBackupSuccess(dir: String) = if (language == AppLanguage.INDONESIAN) "Backup berhasil disimpan di: $dir" else "Backup successfully saved at: $dir"
    fun logTargetJsonId(id: String) = if (language == AppLanguage.INDONESIAN) "Target JSONID: $id" else "Target JSONID: $id"
    fun logTargetAdid(adid: String) = if (language == AppLanguage.INDONESIAN) "Target ADID: $adid" else "Target ADID: $adid"
    val logInputInvalid = if (language == AppLanguage.INDONESIAN) "Error: ID mengandung karakter tidak valid. Hanya angka, huruf a-f, dan '-' yang diizinkan." else "Error: ID contains invalid characters. Only digits, a-f letters, and '-' are allowed."
    val logWarning84Char = if (language == AppLanguage.INDONESIAN) "Peringatan: Panjang ID tidak 84 karakter! Injeksi mungkin gagal di server USA." else "Warning: ID length is not 84 characters! Injection might fail on USA server."
    fun logSplitPrefix(prefix: String) = if (language == AppLanguage.INDONESIAN) "Split Prefix: $prefix" else "Split Prefix: $prefix"
    fun logSplitHex(hex: String) = if (language == AppLanguage.INDONESIAN) "Split Hex: $hex" else "Split Hex: $hex"
    val logProcessingTargetInjection = if (language == AppLanguage.INDONESIAN) "Memproses injeksi file target..." else "Processing target file injection..."
    val logErrPlayerPrefsNotFound = if (language == AppLanguage.INDONESIAN) "Error: File PlayerPrefs tidak ditemukan!" else "Error: PlayerPrefs file not found!"
    val logFixingPermissions = if (language == AppLanguage.INDONESIAN) "Memperbaiki perizinan file..." else "Fixing file permissions..."
    val logDoneSuccess = if (language == AppLanguage.INDONESIAN) "Selesai! DevId berhasil diperbarui." else "Done! DevId updated successfully."
    val logOpenGameInstruction = if (language == AppLanguage.INDONESIAN) "" else "Please open your Mobile Legends game."
    fun logErrorInjection(msg: String) = if (language == AppLanguage.INDONESIAN) "Error selama proses injeksi: $msg" else "Error during injection process: $msg"
    
    val btnSaveId = if (language == AppLanguage.INDONESIAN) "Simpan" else "Save"
    val savedDevIdTitle = if (language == AppLanguage.INDONESIAN) "DEVID TERSIMPAN (PRESET)" else "SAVED DEVIDS (PRESETS)"
    val emptySavedIds = if (language == AppLanguage.INDONESIAN) "Belum ada DevID tersimpan. Klik 'Simpan' untuk menyimpan ID favorit." else "No saved DevIDs yet. Click 'Save' to bookmark favorite IDs."
    val saveIdDialogTitle = if (language == AppLanguage.INDONESIAN) "SIMPAN DEVID" else "SAVE DEVID"
    val labelNamePlaceholder = if (language == AppLanguage.INDONESIAN) "Nama / Label (misal: Akun Utama)" else "Name / Label (e.g. Main Account)"
    val btnSave = if (language == AppLanguage.INDONESIAN) "SIMPAN" else "SAVE"
    val btnCancel = if (language == AppLanguage.INDONESIAN) "BATAL" else "CANCEL"
    val btnUse = if (language == AppLanguage.INDONESIAN) "Gunakan" else "Use"
    val toastSaveSuccess = if (language == AppLanguage.INDONESIAN) "DevID berhasil disimpan!" else "DevID saved successfully!"
    val toastDeleteSuccess = if (language == AppLanguage.INDONESIAN) "DevID berhasil dihapus!" else "DevID deleted successfully!"
    val toastAppliedSuccess = if (language == AppLanguage.INDONESIAN) "DevID tersimpan dipasang di kolom input!" else "Saved DevID set into input field!"
    val labelDevIdToSave = if (language == AppLanguage.INDONESIAN) "DevID yang akan disimpan:" else "DevID to save:"
    val selectPresetLabel = if (language == AppLanguage.INDONESIAN) "Pilih Preset DevID Tersimpan..." else "Select Saved DevID Preset..."
    val noPresets = if (language == AppLanguage.INDONESIAN) "Belum ada preset DevID tersimpan" else "No saved DevID presets"
    fun logDevIdSaved(label: String) = if (language == AppLanguage.INDONESIAN) "DevID tersimpan sebagai '$label'" else "DevID saved as '$label'"
    val logDevIdDeleted = if (language == AppLanguage.INDONESIAN) "DevID dihapus dari daftar simpanan." else "DevID deleted from saved list."
    val logDevIdApplied = if (language == AppLanguage.INDONESIAN) "DevID tersimpan dipasang ke kolom input." else "Saved DevID set to input field."

    val configScreenTitle = if (language == AppLanguage.INDONESIAN) "CONFIG DEVID TERSIMPAN" else "SAVED DEVID CONFIG"
    fun configScreenSubtitle(count: Int) = if (language == AppLanguage.INDONESIAN) "Total $count preset DevID tersimpan" else "Total $count saved DevID presets"
    val btnAddManualDevId = if (language == AppLanguage.INDONESIAN) "Tambah DevID" else "Add DevID"
    val toastAppliedAndNavigated = if (language == AppLanguage.INDONESIAN) "DevID dipasang! Berpindah ke Home..." else "DevID applied! Navigating to Home..."

    val successTitle = if (language == AppLanguage.INDONESIAN) "INJEKSI DEVID BERHASIL!" else "DEVID INJECTION SUCCESSFUL!"
    val successSub = if (language == AppLanguage.INDONESIAN) "Device ID berhasil diperbarui. " else "Device ID updated successfully. Please launch Mobile Legends game."
    val btnOk = "OK"

    val btnOpenGame = if (language == AppLanguage.INDONESIAN) "BUKA ML" else "OPEN ML"
    fun toastGameNotInstalled(name: String) = if (language == AppLanguage.INDONESIAN) "Game MLBB ($name) belum terinstal!" else "MLBB Game ($name) is not installed!"
    val toastInjectionSuccess = if (language == AppLanguage.INDONESIAN) "Injeksi DevID Berhasil! Silakan buka game." else "DevID Injection Successful! Please open the game."
    val toastInjectionError = if (language == AppLanguage.INDONESIAN) "Gagal melakukan injeksi DevID!" else "Failed to inject DevID!"

    val tabCheckId = if (language == AppLanguage.INDONESIAN) "Cek ID" else "Check ID"
    val mlbbCheckTitle = if (language == AppLanguage.INDONESIAN) "CEK ID MLBB" else "MLBB ID CHECKER"
    val mlbbCheckSubtitle = if (language == AppLanguage.INDONESIAN) "Cek nama & region akun Mobile Legends" else "Check Mobile Legends account name & region"
    val mlbbUserIdLabel = if (language == AppLanguage.INDONESIAN) "User ID" else "User ID"
    val mlbbServerIdLabel = if (language == AppLanguage.INDONESIAN) "Server ID (Zone)" else "Server ID (Zone)"
    val mlbbIdHint = if (language == AppLanguage.INDONESIAN) "Masukkan User ID dan Server ID dari profil MLBB kamu (format: ID(server), contoh 123456(1234))" else "Enter the User ID and Server ID from your MLBB profile (format: ID(server), e.g. 123456(1234))"
    val mlbbCheckButton = if (language == AppLanguage.INDONESIAN) "CEK ID MLBB" else "CHECK MLBB ID"
    val mlbbChecking = if (language == AppLanguage.INDONESIAN) "MEMERIKSA..." else "CHECKING..."
    val mlbbResultTitle = if (language == AppLanguage.INDONESIAN) "HASIL PENGECEKAN" else "CHECK RESULT"
    val mlbbResultSuccess = if (language == AppLanguage.INDONESIAN) "AKUN DITEMUKAN" else "ACCOUNT FOUND"
    val mlbbNicknameLabel = if (language == AppLanguage.INDONESIAN) "Nickname" else "Nickname"
    val mlbbCountryLabel = if (language == AppLanguage.INDONESIAN) "Country / Region" else "Country / Region"
    val mlbbUserIdResultLabel = if (language == AppLanguage.INDONESIAN) "User ID" else "User ID"
    val mlbbServerIdResultLabel = if (language == AppLanguage.INDONESIAN) "Server ID" else "Server ID"
    val mlbbErrorTitle = if (language == AppLanguage.INDONESIAN) "GAGAL MENGECEK ID" else "ID CHECK FAILED"
    val mlbbErrorInputEmpty = if (language == AppLanguage.INDONESIAN) "User ID dan Server ID tidak boleh kosong!" else "User ID and Server ID cannot be empty!"
    val mlbbErrorGeneric = if (language == AppLanguage.INDONESIAN) "Gagal memeriksa ID. Coba lagi nanti." else "Failed to check ID. Please try again later."
}

